services:
  browserless:
    build: !reset null
    image: ghcr.io/browserless/chromium:latest
    pull_policy: always

  sandbox-runtime:
    build: !reset null
    image: ghcr.io/yokingma/weclaws/sandbox-runtime:latest
    pull_policy: always
    volumes: !override
      - ${WECLAWS_DATA_ROOT}/sandbox-user-workspaces:/app/apps/sandbox-runtime/user-workspaces
      - ${WECLAWS_DATA_ROOT}/instances:/app/storage/instances
      - ${WECLAWS_DATA_ROOT}/sandbox-runtime-private:/app/storage/sandbox-runtime-private

  supervisor:
    build: !reset null
    image: ghcr.io/yokingma/weclaws/supervisor:latest
    pull_policy: always
    volumes: !override
      - ${WECLAWS_DATA_ROOT}/sqlite:/app/storage/sqlite
      - ${WECLAWS_DATA_ROOT}/instances:/app/storage/instances
      - ${WECLAWS_DATA_ROOT}/sandbox-runtime-private:/app/storage/sandbox-runtime-private

  web:
    build: !reset null
    image: ghcr.io/yokingma/weclaws/web:latest
    pull_policy: always
    volumes: !override
      - ${WECLAWS_DATA_ROOT}/sqlite:/app/storage/sqlite
      - ${WECLAWS_DATA_ROOT}/instances:/app/storage/instances
      - ${WECLAWS_DATA_ROOT}/sandbox-runtime-private:/app/storage/sandbox-runtime-private
